[project]
name = "3d-map-generation-ml-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "scipy>=1.15.1",
]
